name: idact-dev
channels:
  - defaults
dependencies:
  - python=3.6
  - setuptools
  - pip
  - "sphinx>=1.7.4"
  - "pytest-cov>=2.5.1"
  - "click>=6.7"
  - "pytest>=3.5.1"
  - "python-dateutil>=2.7.2"
  - "graphviz>=2.38.0"
  - "nb_conda_kernels>=2.1.0"
  - pip:
    - "fabric3>=1.14"
    - "pytest-flake8>=1.0.1"
    - "pytest-pylint>=0.9.0"
    - "m2r>=0.1.14"
    - "bitmath>=1.3.1.2"
    - "sphinx-autodoc-typehints>=1.3.0"
    - "better-apidoc>=0.1.4"
    - "sphinx-rtd-theme>=0.4.2"
    - "sshtunnel>=0.1.4"
    - "paramiko>=2.4.1"
    - "requests>=2.18.4"
    - "dask>=0.18.2"
    - "distributed>=1.22.0"
    - "bokeh>=0.13.0"
    - "sphinx-click>=1.4.0"
    - "nbsphinx>=0.3.5"
    - "ipython>=6.4.0"
    - "jupyter>=1.0.0"
    - "jupyterlab>=0.35.4"
    - "coveralls>=1.5.1"
    - "pytest-xdist>=1.26.1"
